baseURL = "https://clubcompy.com/comfylang"
languageCode = "en-us"
title = "Comfy Computer Language Documentation"
theme = "ace-documentation"
copyright = '''Woldrich, Inc. - <img alt="Creative Commons License" style="border-width:0" src="/comfylang/images/by-nc-nd.png" />'''
