#!/usr/bin/env bash

/usr/local/bin/asciidoctor \
-v \
-r asciidoctor-html5s \
-r asciidoctor-diagram \
-a source-highlighter=pygments \
-a pygments-linenums-mode=inline \
-a pygments-css=style \
-a pygments-style=monokai "$@" \
-b html5s
