baseURL = "https://clubcompy.com/blog"
languageCode = "en-us"
title = "ClubCompy Blog"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = '''Woldrich, Inc. - <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png" /></a>'''
